### PR TITLE
Add Makefile for static library compilation

### PR DESCRIPTION
**Pull request by platipo**
Unfortunately I cannot test it neither with CUDA nor under Windows.

#56

### CODE REVIEW

**Comment by ihhub** [comment]
Hi, @platipo ,

Thank you for your efforts!

I had a look at your pull request. I have multiple suggestions/remarks:
1. For me compilation failed with such error:
```
mvcc -std=c++11 -c cuda/cuda_device.cu -o cuda/cuda_device.o
make: mvcc: No such file or directory
make: *** [cuda/cuda_device.o] Error 1
```

I tested on MacOS (Unix system) which does not have CUDA library.

2. CUDA compiler is called ```nvcc```, not ```mvcc``` but it doesn't solve the problem above.

3. We should put a makefile out of ```Library``` folder to do not contaminate source folder. I recommend to put makefile under ```build\static_library``` as for now and put all static files there. Ideally copy header files there too because they are needed to use the library.

4. We should include all files inside Library folder without setting specific names of files. Otherwise every time we have to modify makefile once we add/remove some files. This needs some preparations. You didn't include files like ```image_function_sse.cpp``` or ```image_function_neon.cpp``` because of SIMD restrictions. I will change those files in upcoming days that you can include them easily into makefile.

5. Make a pull request for linux build separately. It's a good practice to do separate commits in separate pull request.

**Comment by platipo** [comment]
1. What flags do you use when compiling with `nvcc`? As In stated I cannot verify the CUDA part
2. Done
3. I think it isn't necessary to reinvent the whell, but we should follow a well known [structure](https://stackoverflow.com/questions/1398445/directory-structure-for-a-c-library#1398594). I suggest you to reorganize the codebase
4. I have to wait until you change the structure for SSE, AVX and SIMD and then I can change the makefile
5. You are right, done
